---
dependency:
  name: galaxy
  options:
    ignore-certs: True
    ignore-errors: True
    role-file: requirements.yml

driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: instance
    box: ubuntu/focal64
    provider_raw_config_args:
      - "customize ['modifyvm', :id, '--uartmode1', 'disconnected']"
      - "customize ['modifyvm', :id, '--uart1', '0x3F8', '4']"
      - "customize ['modifyvm', :id, '--cableconnected1', 'on']"

provisioner:
  name: ansible
  playbooks:
      cleanup: cleanup.yml

verifier:
  name: ansible
